import SectionTitle from "../text-stylings/sectionTitle";

export default function Skills({ id }) {
    return (
        <div className="flex flex-col text-center gap-2 " id={id}>
            <SectionTitle>
                Skills
            </SectionTitle>
            <div>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Condimentum lacinia quis vel eros donec ac. Id semper risus in hendrerit gravida rutrum quisque non tellus. Mauris cursus mattis molestie a iaculis at erat. Est sit amet facilisis magna etiam tempor orci eu. Vivamus arcu felis bibendum ut tristique et. Tortor at risus viverra adipiscing at in tellus integer feugiat. Sollicitudin aliquam ultrices sagittis orci. Porttitor leo a diam sollicitudin tempor id. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Ac orci phasellus egestas tellus rutrum. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Duis at consectetur lorem donec massa sapien faucibus.

                Ornare arcu odio ut sem nulla pharetra diam sit. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Porttitor massa id neque aliquam vestibulum. Iaculis urna id volutpat lacus laoreet. Risus commodo viverra maecenas accumsan lacus. Sodales neque sodales ut etiam. A cras semper auctor neque. Viverra adipiscing at in tellus. Faucibus et molestie ac feugiat sed lectus. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Eget nulla facilisi etiam dignissim diam quis enim. Netus et malesuada fames ac turpis egestas integer. Nec ultrices dui sapien eget mi proin sed libero. Nulla pellentesque dignissim enim sit amet venenatis urna cursus. Ut eu sem integer vitae. Dui vivamus arcu felis bibendum ut tristique et egestas. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae.

                Donec massa sapien faucibus et molestie. Eu ultrices vitae auctor eu augue ut lectus arcu bibendum. Nullam non nisi est sit amet facilisis magna. Ultricies integer quis auctor elit sed vulputate mi sit. Dapibus ultrices in iaculis nunc. Quisque id diam vel quam. In est ante in nibh mauris cursus mattis molestie a. Libero volutpat sed cras ornare arcu. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Enim nec dui nunc mattis enim ut tellus elementum sagittis. Et tortor at risus viverra adipiscing at in tellus. Diam volutpat commodo sed egestas egestas fringilla phasellus. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Quam adipiscing vitae proin sagittis nisl. Et odio pellentesque diam volutpat. Egestas pretium aenean pharetra magna ac placerat. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Nisi est sit amet facilisis magna etiam tempor. Posuere sollicitudin aliquam ultrices sagittis orci. Consectetur a erat nam at.

                Elementum pulvinar etiam non quam lacus. Porta nibh venenatis cras sed felis eget. Sed pulvinar proin gravida hendrerit lectus. Nunc mattis enim ut tellus elementum sagittis. Ac tortor vitae purus faucibus ornare suspendisse sed nisi. Ut tristique et egestas quis ipsum suspendisse ultrices. Egestas pretium aenean pharetra magna. Cras ornare arcu dui vivamus arcu felis. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Ornare quam viverra orci sagittis eu. Risus commodo viverra maecenas accumsan lacus vel. Nullam ac tortor vitae purus faucibus ornare. Ullamcorper malesuada proin libero nunc consequat. Sit amet porttitor eget dolor morbi non. Eu lobortis elementum nibh tellus molestie nunc. Sit amet dictum sit amet justo donec enim diam vulputate. Arcu dui vivamus arcu felis bibendum. Et egestas quis ipsum suspendisse ultrices gravida dictum. Sit amet facilisis magna etiam tempor orci eu lobortis elementum.

                Odio ut sem nulla pharetra diam sit amet nisl. Euismod quis viverra nibh cras pulvinar mattis nunc sed. A lacus vestibulum sed arcu non odio euismod lacinia. Ac placerat vestibulum lectus mauris ultrices eros. Morbi non arcu risus quis. Neque volutpat ac tincidunt vitae semper quis lectus. Nec feugiat nisl pretium fusce id velit ut tortor pretium. Risus feugiat in ante metus dictum at. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Donec et odio pellentesque diam volutpat commodo sed. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Interdum posuere lorem ipsum dolor sit amet. In hendrerit gravida rutrum quisque. Mi proin sed libero enim. Tempus egestas sed sed risus pretium quam.
            </div>
        </div>

    )
}